# fly.toml app configuration file generated for gold-rush-frontend on 2025-04-30T12:47:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gold-rush-frontend"

[build]
  builtin = "static"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 80  # ← Fix: was 8080, should be 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
